default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bookbuddy_development
  username: <%= ENV["BOOKBUDDY_DB_USERNAME"] %>
  password: <%= ENV["BOOKBUDDY_DB_PASSWORD"] %>
  host: localhost
  port: 5432

test:
  <<: *default
  database: bookbuddy_test
  username: <%= ENV["BOOKBUDDY_DB_USERNAME"] %>
  password: <%= ENV["BOOKBUDDY_DB_PASSWORD"] %>
  host: localhost
  port: 5432

production:
  primary: &primary_production
    <<: *default
    database: bookbuddy_production
    username: <%= ENV["BOOKBUDDY_DB_USERNAME"] %>
    password: <%= ENV["BOOKBUDDY_DB_PASSWORD"] %>
    host: <%= ENV["BOOKBUDDY_DB_HOST"] %>
  cache:
    <<: *primary_production
    database: bookbuddy_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: bookbuddy_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: bookbuddy_production_cable
    migrations_paths: db/cable_migrate
